/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Gift App
 * Crypto Gift App contest
 * OpenAPI spec version: 1.0
 */
import type { CreateTransactionDtoTransactionType } from './createTransactionDtoTransactionType';

export interface CreateTransactionDto {
  /** Transaction Amount */
  amount: number;
  /** Transaction type */
  transactionType: CreateTransactionDtoTransactionType;
  /** User ID */
  user: string;
}
