/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Gift App
 * Crypto Gift App contest
 * OpenAPI spec version: 1.0
 */

/**
 * Transaction type
 */
export type CreateTransactionDtoTransactionType = typeof CreateTransactionDtoTransactionType[keyof typeof CreateTransactionDtoTransactionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateTransactionDtoTransactionType = {
  send: 'send',
  buy: 'buy',
  receive: 'receive',
} as const;
