/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Gift App
 * Crypto Gift App contest
 * OpenAPI spec version: 1.0
 */

export interface CreateActionDto {
  actionType: string;
  gift: string;
  recipient?: string;
  user: string;
}
