/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Gift App
 * Crypto Gift App contest
 * OpenAPI spec version: 1.0
 */
import type { GiftCurrency } from './giftCurrency';

export interface Gift {
  animationUrl: string;
  availability: number;
  currency: GiftCurrency;
  description?: string;
  imageUrl: string;
  name: string;
  price: number;
  totalIssued: number;
  variant: string;
}
