/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Gift App
 * Crypto Gift App contest
 * OpenAPI spec version: 1.0
 */

export type GiftCurrency = typeof GiftCurrency[keyof typeof GiftCurrency];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GiftCurrency = {
  USDT: 'USDT',
  TON: 'TON',
  ETH: 'ETH',
} as const;
