/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Gift App
 * Crypto Gift App contest
 * OpenAPI spec version: 1.0
 */

export interface Gift {
  animationUrl: string;
  availability: number;
  currency: string;
  description?: string;
  imageUrl: string;
  name: string;
  price: number;
  totalIssued: number;
  variant: string;
}
