/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Gift App
 * Crypto Gift App contest
 * OpenAPI spec version: 1.0
 */
import type { Gift } from './gift';

export interface User {
  fullName: string;
  gifts?: Gift[];
  language?: string;
  profilePhoto?: string;
  purchasedGifts?: Gift[];
  telegramId: number;
  username?: string;
}
