/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Gift App
 * Crypto Gift App contest
 * OpenAPI spec version: 1.0
 */

export type UsersControllerFindAllOrderBy = typeof UsersControllerFindAllOrderBy[keyof typeof UsersControllerFindAllOrderBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersControllerFindAllOrderBy = {
  default: 'default',
  giftCount: 'giftCount',
} as const;
